import javax.swing.JOptionPane;
public class frmArboles extends javax.swing.JFrame {

    /**
     * Creates new form frmArboles
     */
    Arbol A1;
    public frmArboles() {
        initComponents();
        A1= new Arbol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Jta1 = new javax.swing.JTextArea();
        t1 = new javax.swing.JTextField();
        BtnInsertar = new javax.swing.JButton();
        BtnPreOrden = new javax.swing.JButton();
        BtnInOrden = new javax.swing.JButton();
        BtnPostOrden = new javax.swing.JButton();
        BtnSumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jta1.setColumns(20);
        Jta1.setRows(5);
        jScrollPane1.setViewportView(Jta1);

        BtnInsertar.setText("Insertar");
        BtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarActionPerformed(evt);
            }
        });

        BtnPreOrden.setText("PreOrden");
        BtnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPreOrdenActionPerformed(evt);
            }
        });

        BtnInOrden.setText("InOrden");
        BtnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInOrdenActionPerformed(evt);
            }
        });

        BtnPostOrden.setText("PostOrden");
        BtnPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPostOrdenActionPerformed(evt);
            }
        });

        BtnSumar.setText("Sumar");
        BtnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSumar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnPreOrden)
                        .addGap(35, 35, 35)
                        .addComponent(BtnInOrden)
                        .addGap(18, 18, 18)
                        .addComponent(BtnPostOrden))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnInsertar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInsertar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPreOrden)
                    .addComponent(BtnInOrden)
                    .addComponent(BtnPostOrden))
                .addGap(18, 18, 18)
                .addComponent(BtnSumar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarActionPerformed
        // TODO add your handling code here:
        int x;
        x=Integer.parseInt(t1.getText());
        A1.insertar(x);
    }//GEN-LAST:event_BtnInsertarActionPerformed

    private void BtnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPreOrdenActionPerformed
        // TODO add your handling code here:
        A1.preOrden(Jta1);
    }//GEN-LAST:event_BtnPreOrdenActionPerformed

    private void BtnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInOrdenActionPerformed
        // TODO add your handling code here:
        A1.inOrden(Jta1);
    }//GEN-LAST:event_BtnInOrdenActionPerformed

    private void BtnPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPostOrdenActionPerformed
        // TODO add your handling code here:
        A1.postOrden(Jta1);
    }//GEN-LAST:event_BtnPostOrdenActionPerformed

    private void BtnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarActionPerformed
    // TODO add your handling code here:
    int s=A1.sumar();
    JOptionPane.showMessageDialog(rootPane,"la suma es :"+ Integer.toString(s));
    }//GEN-LAST:event_BtnSumarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmArboles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInOrden;
    private javax.swing.JButton BtnInsertar;
    private javax.swing.JButton BtnPostOrden;
    private javax.swing.JButton BtnPreOrden;
    private javax.swing.JButton BtnSumar;
    private javax.swing.JTextArea Jta1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
